spring:
  jpa:
    open-in-view: false
    database: default
    generate-ddl: false
    hibernate:
      ddl-auto: none

    show-sql: true

  flyway:
    enabled: false
    locations: classpath:db/migration/postgres

primary:
  datasource:
    url: jdbc:postgresql://localhost:5432/notesdb
    username: usr
    password: pwd
    driver-class-name: org.postgresql.Driver
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    locations: classpath:db/migration/postgres

secondary:
  datasource:
    url: jdbc:mysql://localhost:3306/users
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
  flyway:
    locations: classpath:/db/migration/mysql

logging:
  level:
    ROOT: ERROR
    org.hibernate.engine.transaction.internal: DEBUG